apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  description: A self-hosted Backstage portal
  annotations:
    backstage.io/techdocs-ref: dir:.    # Keep this if you're planning to use TechDocs
spec:
  type: website
  owner: user: default/InfraNest              # Matches a Backstage user entity
  lifecycle: production


