apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default/wyz
  description: Team WYZ responsible for XYZ services
spec:
  type: team
  profile:
    displayName: Team WYZ
    email: wyztechnologies@gmail.com
  children: []  # You can add sub-teams here
  members:      # Add users here
    - Nithin SK
    - ravish0007_nh
    - Elizabeth
    - Druva S
  parent: engineering  # Optional parent group
